#!/bin/zsh

export ADOTDIR=$HOME/.zsh/antigen
if [[ ! -d $ADOTDIR ]]; then
  mkdir $ADOTDIR
fi

if [[ "$DISTRO" == "darwin" ]]; then
    source /opt/homebrew/share/antigen/antigen.zsh
else
    source /usr/share/zsh-antigen/antigen.zsh
fi

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle scfrazer/zsh-jump-target --branch=master
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle seebi/dircolors-solarized --branch=master

antigen apply

if [[ "$1" == "update" ]]; then
    antigen update
fi
