services:
  debian:
    build: .
    volumes:
      - .:/workspace
    entrypoint: ["tail", "-f", "/dev/null"]
    command: "/bin/bash"
    # Inside the container: chezmoi init --source=/workspace --apply
    stdin_open: true # docker run -i
    tty: true
