#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15

yabai -m rule --add app="iPhone Mirroring" manage=on

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

borders active_color=0xff00B2FF hidpi=on width=5 style=round &
echo "yabai configuration loaded.."
