[[ $- != *i* ]] && return

setopt extendedglob


# Call all files in .zsh, except .zwc (generated by antigen)
for rc in $HOME/.zsh/*~*.zwc; do
    source $rc
done

dirColorsSolarizedDir="bundles/seebi/dircolors-solarized-master/dircolors.256dark"
if [ -r $ADOTDIR/$dirColorsSolarizedDir ]; then
    eval $(dircolors $ADOTDIR/$dirColorsSolarizedDir);
fi

if [ -r $HOME/.custom ]; then
    source $HOME/.custom;
fi

unsetopt extendedglob
