[[ $- != *i* ]] && return

setopt extendedglob


# Call all files in .zsh, except .zwc (generated by antigen)
for rc in $HOME/.zsh/*~*.zwc; do
    source $rc
done

if [ -r $ADOTDIR/seebi/dircolors-solarized/dircolors.256dark ]; then
    eval $(dircolors ADOTDIR/seebi/dircolors-solarized/dircolors.256dark);
fi

if [ -r $HOME/.custom ]; then
    source $HOME/.custom;
fi

unsetopt extendedglob
